# Generated by Django 5.0.2 on 2024-02-16 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_remove_staff_department'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AssetTransfer',
        ),
    ]
