# Generated by Django 5.0.2 on 2024-02-23 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_useraction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraction',
            name='action',
            field=models.TextField(),
        ),
    ]
