# Generated by Django 5.0.2 on 2024-02-16 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_asset_is_written_off_department_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assettype',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
