# Generated by Django 5.0.2 on 2024-02-26 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_asset_written_off_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetassignment',
            name='assignment_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
