# Generated by Django 5.0.2 on 2024-02-26 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_alter_assetassignment_assignment_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assetassignment',
            old_name='assignment_date_by',
            new_name='assignment_by',
        ),
        migrations.RenameField(
            model_name='assetassignment',
            old_name='return_date_by',
            new_name='return_by',
        ),
    ]
