# Generated by Django 5.0.2 on 2024-03-06 09:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0008_usersettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersettings',
            name='setting1',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='setting2',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='setting3',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='setting4',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='setting5',
        ),
        migrations.AddField(
            model_name='usersettings',
            name='accessibility_options',
            field=models.CharField(default='High contrast', max_length=255),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='add_confirmation',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='dark_mode_theme',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='delete_confirmation',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='desktop_theme',
            field=models.CharField(default='Green animation', max_length=255),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='display_language',
            field=models.CharField(default='Russian', max_length=255),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='email_notifications',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='font',
            field=models.CharField(default='Helvetica', max_length=255),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='font_size',
            field=models.IntegerField(default=11),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='notification_frequency',
            field=models.CharField(default=True, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usersettings',
            name='notification_sound',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='update_confirmation',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
